name: CI

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: goodsmileduck/yandex-serverless-action@master
      env:
        SOURCE_DIR: '.'
        ZONE: 'ru-central1-a'
        FUNCTION_ID: ${{ secrets.CLOUD_ID }}
        FUNCTION_NAME: 'handler'
        CLOUD_ID: ${{ secrets.CLOUD_ID }}
        FOLDER_ID: ${{ secrets.FOLDER_ID }}
        TOKEN: ${{ secrets.TOKEN }}
        BUCKET: ${{ secrets.BUCKET }}
        ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
